project:
  type: website

website:
  title: "Ullrika's course material for BERN02"
#  subtitle: "Computational Science: Reproducible Data Science and Statistical Learning"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: pages/L1_intro_supervised_learning.qmd
        text: Introduction 
      - href: pages/L1_linear_regression.qmd
        text: Linear regression
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



