---
title: "Exercise Hierarchical models and testing"
subtitle: "BERN02"
author: "Ullrika Sahlin"
format: 
  html:
    embed-resources: true
    theme: cosmo
echo: false
---

## Format

Work individually or in pairs. If you work in a pair, each person hand in individually, but write in the beginning of the file you hand in whom you have been working with. 

## Time needed

The coding part of this exercise is expected to **not** take more than eight hours to complete. 

The peer-review is expected to take not more than two hours. 

## Peer-review

You are to peer-review another student report. The purpose of this part is that you are to practice reading code made by someone else and practice giving constructive and helpful comments on code. 

Limit your peer-review to comments on these four points: 

1. the choice and justification of the model
2. the method for estimation and its implementation
3. the method for testing and the reliability of the results
4. the readability of the report

Which report to review is assigned by Ullrika. One report can receive several reviewers. You cannot do a review, until you have submitted your own report. 

Note that the review is also graded. 

## Grades

Pass or Fail. To pass, the student must hand in their own report and provide a peer-review on another student report. Both reports must be of acceptable quality. 

## Programming language

You can use the language you prefer, but I recommend using *R* or *Python*. 

## Problem: Evidence synthesis

We are going to use a data set of a collection of randomised case-control studies of the effectiveness of descriptive social norms on hotel customers behavior to reuse their towels. 

Read Scheibehenne et al. (2016) to understand why and how the studies were conducted. 

Scheibehenne, B., Jamil, T., & Wagenmakers, E.-J. (2016). Bayesian Evidence Synthesis Can Reconcile Seemingly Inconsistent Results: The Case of Hotel Towel Reuse. Psychological Science, 27(7), 1043-1046. [https://journals.sagepub.com/doi/10.1177/0956797616644081](https://journals.sagepub.com/doi/10.1177/0956797616644081)

You task is to formulate and justify a parametric model for testing the effectiveness of the intervention, estimate the model parameters and test if the intervention has an effect or not. 

(@) The model should use an appropriate family distribution for the response variable, and

(@) consider between study heterogeneity. 

(@) Estimate parameters using Bayesian inference (believe me - it is easier). You can write your own code **or use ready available functions in suitable packages** (highly recommended). 

::: callout-tip
## Software

User friendly software for Bayesian inference with hierarchical models 

- in R [brms](https://paulbuerkner.com/brms/)

More specifically, you can see how to specify [a model with binomial response](https://bookdown.org/ajkurz/Statistical_Rethinking_recoded/counting-and-classification.html#binomial-regression)

There is useful code examples on this information about [Bayesian meta analysis using brms](https://bookdown.org/MathiasHarrer/Doing_Meta_Analysis_in_R/bayesian-ma.html)

- in Python [bambi](https://bambinos.github.io/bambi/)

More specifically, [an hierarhical model with binomial response](https://bambinos.github.io/bambi/notebooks/hierarchical_binomial_bambi.html#hierarchical-model)

:::


(@) Make a summary of the parameter values by the posterior mean and 90% probability interval. 

(@) Formulate hypotheses for the test of the effectiveness of the intervention referring to one or several parameters within the model. 

(@) Test the hypothesis using Bayesian inference. 

::: callout-tip
## Tips for data wrangling

Study how data are to be entered into the software of your choice, then make sure data has that format.  

A lot can be gained by turning the data from short to long format. Example of code snippets are

In R: 

```{r}
#| eval: false
#| echo: true

library(readr)
library(tidyr)
library(dplyr)
towel_data <- read_delim("towelData.csv", delim = ";", show_col_types = FALSE) %>%
pivot_wider(names_from = Towel.Reuse, values_from = Count) %>%
  mutate(Total=Yes+No)
```

In Python: 

```{python}
#| eval: false
#| echo: true

# read in data
data_file = "towelData.csv"
data = pd.read_csv(data_file, sep=';', encoding='latin1')
count = data.iloc[:, -1] # get the last column with numbers or yes/no

# count has the number of yes and no for control and social norm groups
control_yes = count[::4].to_numpy() # every 4th starting from 0 - control group + yes
control_no = count[2::4].to_numpy() # every 4th starting from 2 - control group + no
control_total = np.array([y + n for y, n in zip(control_yes, control_no)])

social_yes = count[1::4].to_numpy() # every 4th starting from 1 - social norm group + yes
social_no = count[3::4].to_numpy() # every 4th starting from 3 - social norm group + no
social_total = np.array([y + n for y, n in zip(social_yes, social_no)])

study = np.arange(1,len(control_yes)+1) # 7 diferent studies

control_data = pd.DataFrame({"reuse": control_yes, "total": control_total, "group": "control", "study": study})
social_data = pd.DataFrame({ "reuse": social_yes, "total": social_total, "group": "social", "study": study})

combined_data = pd.concat([control_data, social_data], ignore_index=True)

# Convert data types - important for bambi that they are correctly set 
# can give errors otherwise
combined_data['reuse'] = combined_data['reuse'].astype(int)
combined_data['total'] = combined_data['total'].astype(int)
combined_data['group'] = combined_data['group'].astype('category')
combined_data['study'] = combined_data['study'].astype('category')

```



:::


## Submit lab report on Canvas

(1) Write your code so that it is clearly documented, and readable for someone else than yourself. 

:::{callout-tip}

## Literate programming

We recommend integrating sections of code (R or Python) with sections of text using Markdown language. For example: 

- Python in Jupyter Notebook on Google Colab 

- R in Quarto on posit.cloud or Rstudio downloaded to your computer. 
:::

(2) Write your name and date in the heading of the report and, if applicable, the name of your collaborator. 

(3) Submit the report. There are two ways to submit the report 

 - Upload the report in the assignment *Exercise: Hierarchical models and testing* on Canvas. 

  - Use your private git repository for the course. Push your code to git and send a link to the repository in the assignment *Exercise: Hierarchical models and testing* on Canvas. Make sure that the person reviewing your report can see it. 

## Peer review

You are to peer-review another student report. The purpose of this part is that you are to practice reading code and surrounding text made by someone else and practice giving constructive and helpful comments on code. 

Limit your peer-review to comments on these four points: 

1. the choice and justification of the model
2. the method for estimation and its implementation
3. the method for testing and the reliability of the results
4. the readability of the report

You write a report and upload to canvas (preferred option) or type in text into canvas. 

The time you spend on the review should be at maximum three hours

Submit your peer-review on Oct 5 the latest

<!-- https://www.britishecologicalsociety.org/wp-content/uploads/2019/06/BES-Guide-Reproducible-Code-2019.pdf?utm_source=web&utm_medium=web&utm_campaign=better_science -->
